# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cliente.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 460)
        Dialog.setMinimumSize(QtCore.QSize(460, 310))
        Dialog.setMaximumSize(QtCore.QSize(460, 460))
        self.telFixo_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.telFixo_lineEdit.setGeometry(QtCore.QRect(20, 250, 201, 28))
        self.telFixo_lineEdit.setMaxLength(13)
        self.telFixo_lineEdit.setPlaceholderText("")
        self.telFixo_lineEdit.setObjectName("telFixo_lineEdit")
        self.telMovel_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.telMovel_lineEdit.setGeometry(QtCore.QRect(20, 340, 201, 28))
        self.telMovel_lineEdit.setMaxLength(14)
        self.telMovel_lineEdit.setPlaceholderText("")
        self.telMovel_lineEdit.setObjectName("telMovel_lineEdit")
        self.cpf_label = QtWidgets.QLabel(Dialog)
        self.cpf_label.setGeometry(QtCore.QRect(20, 50, 58, 16))
        self.cpf_label.setObjectName("cpf_label")
        self.telFixo_label = QtWidgets.QLabel(Dialog)
        self.telFixo_label.setGeometry(QtCore.QRect(20, 230, 81, 16))
        self.telFixo_label.setObjectName("telFixo_label")
        self.nome_label = QtWidgets.QLabel(Dialog)
        self.nome_label.setGeometry(QtCore.QRect(20, 140, 58, 16))
        self.nome_label.setObjectName("nome_label")
        self.nome_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.nome_lineEdit.setGeometry(QtCore.QRect(20, 160, 201, 28))
        self.nome_lineEdit.setMaxLength(75)
        self.nome_lineEdit.setObjectName("nome_lineEdit")
        self.telMovel_label = QtWidgets.QLabel(Dialog)
        self.telMovel_label.setGeometry(QtCore.QRect(20, 320, 101, 16))
        self.telMovel_label.setObjectName("telMovel_label")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(145, 410, 190, 34))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.cpf_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.cpf_lineEdit.setGeometry(QtCore.QRect(20, 70, 201, 28))
        self.cpf_lineEdit.setMaxLength(14)
        self.cpf_lineEdit.setPlaceholderText("")
        self.cpf_lineEdit.setObjectName("cpf_lineEdit")
        self.dadosBancarios_label = QtWidgets.QLabel(Dialog)
        self.dadosBancarios_label.setGeometry(QtCore.QRect(250, 20, 101, 16))
        self.dadosBancarios_label.setObjectName("dadosBancarios_label")
        self.conta_label = QtWidgets.QLabel(Dialog)
        self.conta_label.setGeometry(QtCore.QRect(320, 100, 51, 16))
        self.conta_label.setObjectName("conta_label")
        self.agencia_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.agencia_lineEdit.setGeometry(QtCore.QRect(260, 120, 51, 28))
        self.agencia_lineEdit.setObjectName("agencia_lineEdit")
        self.banco_comboBox = QtWidgets.QComboBox(Dialog)
        self.banco_comboBox.setGeometry(QtCore.QRect(260, 60, 181, 28))
        self.banco_comboBox.setObjectName("banco_comboBox")
        self.poupanca_radioButton = QtWidgets.QRadioButton(Dialog)
        self.poupanca_radioButton.setGeometry(QtCore.QRect(350, 160, 81, 28))
        self.poupanca_radioButton.setObjectName("poupanca_radioButton")
        self.corrente_radioButton = QtWidgets.QRadioButton(Dialog)
        self.corrente_radioButton.setGeometry(QtCore.QRect(260, 160, 81, 28))
        self.corrente_radioButton.setObjectName("corrente_radioButton")
        self.agencia_label = QtWidgets.QLabel(Dialog)
        self.agencia_label.setGeometry(QtCore.QRect(260, 100, 51, 16))
        self.agencia_label.setObjectName("agencia_label")
        self.conta_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.conta_lineEdit.setGeometry(QtCore.QRect(320, 120, 121, 28))
        self.conta_lineEdit.setObjectName("conta_lineEdit")
        self.banco_label = QtWidgets.QLabel(Dialog)
        self.banco_label.setGeometry(QtCore.QRect(260, 50, 101, 16))
        self.banco_label.setObjectName("banco_label")
        self.endereco_label = QtWidgets.QLabel(Dialog)
        self.endereco_label.setGeometry(QtCore.QRect(250, 190, 101, 16))
        self.endereco_label.setObjectName("endereco_label")
        self.rua_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.rua_lineEdit.setGeometry(QtCore.QRect(260, 240, 121, 28))
        self.rua_lineEdit.setObjectName("rua_lineEdit")
        self.rua_label = QtWidgets.QLabel(Dialog)
        self.rua_label.setGeometry(QtCore.QRect(260, 220, 58, 16))
        self.rua_label.setObjectName("rua_label")
        self.n_label = QtWidgets.QLabel(Dialog)
        self.n_label.setGeometry(QtCore.QRect(390, 220, 21, 16))
        self.n_label.setObjectName("n_label")
        self.n_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.n_lineEdit.setGeometry(QtCore.QRect(390, 240, 41, 28))
        self.n_lineEdit.setObjectName("n_lineEdit")
        self.cidade_label = QtWidgets.QLabel(Dialog)
        self.cidade_label.setGeometry(QtCore.QRect(260, 280, 58, 16))
        self.cidade_label.setObjectName("cidade_label")
        self.cidade_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.cidade_lineEdit.setGeometry(QtCore.QRect(260, 300, 121, 28))
        self.cidade_lineEdit.setObjectName("cidade_lineEdit")
        self.estado_label = QtWidgets.QLabel(Dialog)
        self.estado_label.setGeometry(QtCore.QRect(390, 280, 41, 16))
        self.estado_label.setObjectName("estado_label")
        self.estado_comboBox = QtWidgets.QComboBox(Dialog)
        self.estado_comboBox.setGeometry(QtCore.QRect(390, 300, 41, 28))
        self.estado_comboBox.setObjectName("estado_comboBox")
        self.nome_label_2 = QtWidgets.QLabel(Dialog)
        self.nome_label_2.setGeometry(QtCore.QRect(260, 340, 58, 16))
        self.nome_label_2.setObjectName("nome_label_2")
        self.nome_lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.nome_lineEdit_2.setGeometry(QtCore.QRect(260, 360, 181, 28))
        self.nome_lineEdit_2.setMaxLength(9)
        self.nome_lineEdit_2.setObjectName("nome_lineEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.telFixo_lineEdit.setInputMask(_translate("Dialog", "(99)9999-9999"))
        self.telMovel_lineEdit.setInputMask(_translate("Dialog", "(99)99999-9999"))
        self.cpf_label.setText(_translate("Dialog", "CPF"))
        self.telFixo_label.setText(_translate("Dialog", "Telefone Fixo"))
        self.nome_label.setText(_translate("Dialog", "Nome"))
        self.telMovel_label.setText(_translate("Dialog", "Telefone Móvel"))
        self.cpf_lineEdit.setInputMask(_translate("Dialog", "999.999.999-99"))
        self.dadosBancarios_label.setText(_translate("Dialog", "Dados Bancários"))
        self.conta_label.setText(_translate("Dialog", "Conta"))
        self.agencia_lineEdit.setInputMask(_translate("Dialog", "9999"))
        self.poupanca_radioButton.setText(_translate("Dialog", "Poupança"))
        self.corrente_radioButton.setText(_translate("Dialog", "Corrente"))
        self.agencia_label.setText(_translate("Dialog", "Agência"))
        self.conta_lineEdit.setInputMask(_translate("Dialog", "9999999999"))
        self.banco_label.setText(_translate("Dialog", "Banco"))
        self.endereco_label.setText(_translate("Dialog", "Endereço"))
        self.rua_label.setText(_translate("Dialog", "Rua"))
        self.n_label.setText(_translate("Dialog", "Nº"))
        self.cidade_label.setText(_translate("Dialog", "Cidade"))
        self.estado_label.setText(_translate("Dialog", "Estado"))
        self.nome_label_2.setText(_translate("Dialog", "CEP"))
        self.nome_lineEdit_2.setInputMask(_translate("Dialog", "99999-999"))

