bancos = {
	'Advanced Corretora de Câmbio Ltda. ': '117',
	'Albatross Corretora de Câmbio e Valores S.A ': '172',
	'Ativa Investimentos S.A. Corretora de Títulos Câmbio e Valores': '188',
	'Banco A.J. Renner S.A.': '654',
	'Banco ABC Brasil S.A.': '246',
	'Banco ABN Amro S.A.': '075',
	'Banco Agibank S.A.': '121',
	'Banco Alfa S.A.': '025',
	'Banco Alvorada S.A.': '641',
	'Banco Andbank (Brasil) S.A.': '065',
	'Banco Arbi S.A.': '213',
	'Banco Bandepe S.A.': '024',
	'Banco Barclays S.A.': '740',
	'Banco BM&FBovespa': '096',
	'Banco BMG S.A.': '318',
	'Banco BNP Paribas Brasil S.A.': '752',
	'Banco Boavista Interatlântico S.A.': '248',
	'Banco Bocom BBM S.A. ': '107',
	'Banco Bradescard S.A.': '063',
	'Banco Bradesco BBI S.A.': '036',
	'Banco Bradesco BERJ S.A.': '122',
	'Banco Bradesco Cartões S.A.': '204',
	'Banco Bradesco Financiamentos S.A.': '394',
	'Banco Bradesco S.A.': '237',
	'Banco Brasil Plural S.A. – Banco Múltiplo': '125',
	'Banco Brasileiro de Negócios S.A. – BBN': '081',
	'Banco BS2 S.A.': '218',
	'Banco BTG Pactual S.A.': '208',
	'Banco Caixa Geral – Brasil S.A.': '473',
	'Banco Capital S.A.': '412',
	'Banco Cargill S.A.': '040',
	'Banco Cédula S.A.': '266',
	'Banco Cetelem S.A.': '739',
	'Banco Cifra S.A.': '233',
	'Banco Citibank S.A.': '745',
	'Banco Clássico S.A.': '241',
	'Banco Confidence de Câmbio S.A.': '095',
	'Banco Cooperativo do Brasil S.A. – Bancoob': '756',
	'Banco Cooperativo Sicredi S.A.': '748',
	'Banco Credit Agricole Brasil S.A.': '222',
	'Banco Credit Suisse (Brasil) S.A.': '505',
	'Banco Crefisa S.A.': '069',
	'Banco da Amazônia S.A.': '003',
	'Banco da China Brasil S.A.': '083',
	'Banco Daycoval S.A.': '707',
	'Banco de Brasília S.A. (BRB)': '070',
	'Banco de Crédito e Varejo S.A. – BCV': '250',
	'Banco de Investimento Credit Suisse (Brasil) S.A.': '505',
	'Banco de La Nacion Argentina': '300',
	'Banco de La Provincia de Buenos Aires': '495',
	'Banco de La Republica Oriental del Uruguay': '494',
	'Banco do Brasil S.A.': '001',
	'Banco do Estado de Sergipe S.A.': '047',
	'Banco do Estado do Espírito Santo – Baneste S.A.': '021',
	'Banco do Estado do Pará S.A.': '037',
	'Banco do Estado do Rio Grande do Sul S.A.': '041',
	'Banco do Nordeste do Brasil S.A.': '004',
	'Banco Fator S.A.': '265',
	'Banco Fibra S.A.': '224',
	'Banco Ficsa S.A.': '626',
	'Banco Finaxis S.A.': '094',
	'Banco Guanabara S.A.': '612',
	'Banco Inbursa S.A.': '012',
	'Banco Industrial do Brasil S.A.': '604',
	'Banco Indusval S.A.': '653',
	'Banco Inter S.A.': '077',
	'Banco Intercap S.A.': '630',
	'Banco Internacional do Funchal (Brasil) S.A. – Banif': '719',
	'Banco Investcred Unibanco S.A.': '249',
	'Banco Itaú BBA S.A.': '184',
	'Banco Itaú Consignado S.A.': '029',
	'Banco Itaú Unibanco Holding S.A.': '652',
	'Banco Itaú Unibanco S.A.': '341',
	'Banco ItauBank S.A': '479',
	'Banco J. P. Morgan S.A.': '376',
	'Banco J. Safra S.A.': '074',
	'Banco John Deere S.A.': '217',
	'Banco KDB S.A.': '076',
	'Banco Keb Hana do Brasil S.A.': '757',
	'Banco Luso Brasileiro S.A.': '600',
	'Banco Máxima S.A.': '243',
	'Banco Mercantil do Brasil S.A.': '389',
	'Banco Mizuho do Brasil S.A.': '370',
	'Banco Modal S.A.': '746',
	'Banco Morgan Stanley S.A.': '066',
	'Banco MUFG Brasil S.A.': '456',
	'Banco Nacional de Desenvolvimento Econômico e Social – BNDES': '007',
	'Banco Neon S.A.': '735',
	'Banco Olé Bonsucesso Consignado S.A.': '169',
	'Banco Original do Agronegócio S.A.': '079',
	'Banco Original S.A.': '212',
	'Banco Ourinvest S.A.': '712',
	'Banco Pan S.A.': '623',
	'Banco Paulista S.A.': '611',
	'Banco Pine S.A.': '643',
	'Banco Rabobank International Brasil S.A.': '747',
	'Banco Randon S.A.': '088',
	'Banco Rendimento S.A.': '633',
	'Banco Ribeirão Preto S.A.': '741',
	'Banco Rodobens S.A.': '120',
	'Banco Safra S.A.': '422',
	'Banco Santander (Brasil) S.A.': '033',
	'Banco Semear S.A.': '743',
	'Banco Sistema S.A.': '754',
	'Banco Société Générale Brasil S.A.': '366',
	'Banco Sofisa S.A.': '637',
	'Banco Sumitomo Mitsui Brasileiro S.A.': '464',
	'Banco Topázio S.A.': '082',
	'Banco Triângulo S.A.': '634',
	'Banco Tricury S.A.': '018',
	'Banco Votorantim S.A.': '655',
	'Banco VR S.A.': '610',
	'Banco Western Union do Brasil S.A.': '119',
	'Banco Woori Bank do Brasil S.A.': '124',
	'Bank of America Merrill Lynch Banco Múltiplo S.A.': '755',
	'Barigui Companhia Hipotecária': '268',
	'Bexs Banco de Câmbio S.A. ': '144',
	'Bexs Corretora de Câmbio S.A.': '253',
	'BGC Liquidez Distribuidora de Títulos e Valores Mobiliários Ltda. ': '134',
	'BNY Mellon Banco S.A.': '017',
	'BR Partners Banco de Investimento S.A. ': '126',
	'Brickell (BRK) S.A. Crédito, Financiamento e Investimento': '092',
	'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A. ': '173',
	'Broker Brasil Corretora de Câmbio Ltda. ': '142',
	'BT Corretora de Câmbio Ltda. ': '080',
	'Caixa Econômica Federal': '104',
	'Caruana S.A. Sociedade de Crédito, Financiamento e Investimento ': '130',
	'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor': '159',
	'Central Cooperativa de Crédito no Estado do Espírito Santo – CECOOP': '114',
	'Central de Cooperativas de Economia e Crédito Mútuo do Estado RS – Unicred ': '091',
	'China Construction Bank (Brasil) Banco Múltiplo S.A.': '320',
	'Citibank N.A.': '477',
	'Codepe Corretora de Valores e Câmbio S.A. ': '127',
	'Commerzbank Brasil S.A. – Banco Múltiplo': '163',
	'Confederação Nacional das Cooperativas Centrais Unicred Ltda (Unicred do Brasil)': '136',
	'Confidence Corretora de Câmbio S.A.': '060',
	'Cooperativa Central de Crédito Noroeste Brasileiro Ltda. (CentralCredi)': '097',
	'Cooperativa Central de Crédito Urbano – Cecred': '085',
	'Cooperativa de Crédito Mútuo dos Despachantes de Trânsito de Sta.Catarina e RS': '016',
	'Cooperativa de Crédito Rural da Região da Mogiana': '089',
	'Credicoamo Crédito Rural Cooperativa': '010',
	'Credit Suisse Hedging-Griffo Corretora de Valores S.A.': '011',
	'Cresol – Confederação Nacional Cooperativas Centrais de Crédito e Econ Familiar': '133',
	'Dacasa Financeira S/A – Sociedade de Crédito, Financiamento e Investimento ': '182',
	'Deutsche Bank S.A. – Banco Alemão': '487',
	'Easynvest – Título Corretora de Valores SA ': '140',
	'Facta Financeira S.A. – Crédito Financiamento e Investimento': '149',
	'Fair Corretora de Câmbio S.A. ': '196',
	'Get Money Corretora de Câmbio S.A.': '138',
	'Goldman Sachs do Brasil Banco Múltiplo S.A.': '064',
	'Gradual Corretora de Câmbio, Títulos e Valores Mobiliários S.A. ': '135',
	'Guide Investimentos S.A. Corretora de Valores': '177',
	'Guitta Corretora de Câmbio Ltda. ': '146',
	'Haitong Banco de Investimento do Brasil S.A. ': '078',
	'Hipercard Banco Múltiplo S.A.': '062',
	'HS Financeira S/A Crédito, Financiamento e Investimentos': '189',
	'HSBC Brasil S.A. Banco de Investimento': '269',
	'IB Corretora de Câmbio, Títulos e Valores Mobiliários Ltda. ': '271',
	'ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda. ': '157',
	'ICBC do Brasil Banco Múltiplo S.A.': '132',
	'ING Bank N.V.': '492',
	'Intesa Sanpaolo Brasil S.A. – Banco Múltiplo': '139',
	'JPMorgan Chase Bank, National Association': '488',
	'Kirton Bank S.A. (Banco Múltiplo)': '399',
	'Lecca Crédito, Financiamento e Investimento S/A': '105',
	'Levycam – Corretora de Câmbio e Valores Ltda. ': '145',
	'Magliano S.A. Corretora de Cambio e Valores Mobiliarios ': '113',
	'MS Bank S.A. Banco de Câmbio': '128',
	'Multimoney Corretora de Câmbio Ltda': '137',
	'Natixis Brasil S.A. Banco Múltiplo': '014',
	'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda. ': '191',
	'Novo Banco Continental S.A. – Banco Múltiplo': '753',
	'Nu Pagamentos S.A': '260',
	'Oliveira Trust Distribuidora de Títulos e Valores Mobiliários S.A. ': '111',
	'Omni Banco S.A. ': '613',
	'Paraná Banco S.A.': '254',
	'Parmetal Distribuidora de Títulos e Valores Mobiliários Ltda. ': '194',
	'Pernambucanas Financiadora S.A. Crédito, Financiamento e Investimento': '174',
	'Planner Corretora de Valores S.A.': '100',
	'Pólocred Sociedade de Crédito ao Microempreendedor e Empresa de Pequeno Porte': '093',
	'PortoCred S.A. Crédito, Financiamento e Investimento': '108',
	'Renascença Distribuidora de Títulos e Valores Mobiliários Ltda. ': '101',
	'Scotiabank Brasil S.A. Banco Múltiplo': '751',
	'Senso Corretora de Câmbio e Valores Mobiliários S.A. ': '545',
	'Servicoop – Cooperativa de Economia e Crédito Mútuo dos Servidores Públicos Estaduais do Rio': '190',
	'Socred S.A. – Sociedade de Crédito ao Microempreendedor': '183',
	'Standard Chartered Bank (Brasil) S.A. Banco de Investimento': '118',
	'Stone Pagamentos S.A. ': '197',
	'Treviso Corretora de Câmbio S.A. ': '143',
	'Tullett Prebon Brasil Corretora de Valores e Câmbio Ltda. ': '131',
	'UBS Brasil Banco de Investimento S.A.': '129',
	'UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.': '015',
	'Uniprime Central – Central Interestadual de Cooperativas de Crédito Ltda.': '099',
	'Uniprime Norte do Paraná – Cooperativa de Crédito Ltda. ': '084',
	'XP Investimentos Corretora de Câmbio, Títulos e Valores Mobiliários S/A': '102'
}
estados = ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']
