---FESTA

--listar
SELECT F.CLIENTE, F.DATA, F.NUMERO_CONVIDADOS, F.PRECO, F.GERENTE, F.CASA_FESTA, A.NOME_ANIVERSARIANTE, A.TEMA, A.FAIXA_ETARIA, COUNT(GF.GARCOM)
FROM FESTA F JOIN ANIVERSARIO A ON A.CLIENTE = F.CLIENTE AND A.DATA = F.DATA
LEFT JOIN GARCOM_FESTA GF ON (GF.DATA = A.DATA AND GF.CLIENTE = A.CLIENTE)
GROUP BY(F.CLIENTE, F.DATA, F.NUMERO_CONVIDADOS, F.PRECO, F.GERENTE, F.CASA_FESTA, A.NOME_ANIVERSARIANTE, A.TEMA, A.FAIXA_ETARIA);
	

--listar garcons de uma festa especifica
SELECT FU.NOME, GF.GARCOM AS CPF, FU.COMISSAO FROM
FESTA F JOIN GARCOM_FESTA GF ON (F.CLIENTE = GF.CLIENTE AND F.DATA = GF.DATA)
AND (F.CLIENTE = '165.928.307-86' AND F.DATA = TO_DATE('23/09/2018', 'DD/MM/YYYY'))
JOIN FUNCIONARIO FU ON FU.CPF = GF.GARCOM;

--lista barracas de uma festa especifica
SELECT B.NUMERO, FU.NOME, B.OPERADOR AS CPF, FU.COMISSAO FROM
FESTA F JOIN BARRACA_RASPADINHA B ON (F.CLIENTE = B.CLIENTE AND F.DATA = B.DATA)
AND (F.CLIENTE = '165.928.307-86' AND F.DATA = TO_DATE('23/09/2018', 'DD/MM/YYYY'))
JOIN FUNCIONARIO FU ON FU.CPF = B.OPERADOR;

--endereco da casa de festa de uma festa especifica
SELECT E.RUA, E.NUMERO, E.CEP, E.CIDADE, E.ESTADO FROM
FESTA F JOIN CASA_FESTA CF ON (F.CASA_FESTA = CF.NOME)
AND (F.CLIENTE = '165.928.307-86' AND F.DATA = TO_DATE('31/12/2018', 'DD/MM/YYYY'))
JOIN ENDERECO E ON E.ID = CF.ENDERECO;

--mostrar todos os garcons livres no dia
SELECT F.NOME, F.CPF, F.COMISSAO FROM FUNCIONARIO F WHERE UPPER(F.CARGO) = 'GARCOM' AND
F.CPF NOT IN(
SELECT GF.GARCOM FROM GARCOM_FESTA GF WHERE GF.DATA = TO_DATE('23/09/2018', 'DD/MM/YYYY'));

--operadores de raspadinha livres no dia
SELECT F.NOME, F.CPF, F.COMISSAO FROM FUNCIONARIO F WHERE UPPER(F.CARGO) = 'OPERADOR' AND
F.CPF NOT IN(
SELECT BR.OPERADOR FROM BARRACA_RASPADINHA BR WHERE BR.DATA = TO_DATE('23/09/2018', 'DD/MM/YYYY'));

--gerentes livres no dia da festa
SELECT F.NOME, F.CPF, F.COMISSAO FROM FUNCIONARIO F WHERE UPPER(F.CARGO) = 'GERENTE' AND
F.CPF NOT IN(
SELECT FE.GERENTE FROM FESTA FE WHERE FE.DATA = TO_DATE('23/09/2018', 'DD/MM/YYYY'));

--mostrar todas as casas de festa
SELECT NOME FROM CASA_FESTA;



--FUNCIONARIOS


--listar gerente
SELECT F.CPF, F.NOME, F.TEL_MOVEL, F.TEL_FIXO, F.COMISSAO, MIN(FE.DATA) AS DATA_PROXIMA_FESTA
FROM FUNCIONARIO F LEFT JOIN FESTA FE ON FE.GERENTE = F.CPF WHERE UPPER(F.CARGO) = 'GERENTE'
GROUP BY(F.CPF, F.NOME, F.TEL_MOVEL,  F.TEL_FIXO, F.COMISSAO);

--listar operador
SELECT F.CPF, F.NOME, F.TEL_MOVEL, F.TEL_FIXO, F.COMISSAO, MIN(BR.DATA) AS DATA_PROXIMA_FESTA 
FROM FUNCIONARIO F LEFT JOIN BARRACA_RASPADINHA BR ON BR.OPERADOR = F.CPF WHERE UPPER(F.CARGO) = 'OPERADOR'
GROUP BY(F.CPF, F.NOME, F.TEL_MOVEL,  F.TEL_FIXO, F.COMISSAO);

--listar garcom
SELECT F.CPF, F.NOME, F.TEL_MOVEL, F.TEL_FIXO, F.COMISSAO, MIN(GF.DATA) AS DATA_PROXIMA_FESTA
FROM FUNCIONARIO F LEFT JOIN GARCOM_FESTA GF ON GF.GARCOM = F.CPF WHERE UPPER(F.CARGO) = 'GARCOM'
GROUP BY(F.CPF, F.NOME, F.TEL_MOVEL,  F.TEL_FIXO, F.COMISSAO);


--BEBIDAS

--listar dentro dos limites
SELECT B.NOME, B.VOLUME, B.QUANTIDADE, B.PRECO FROM BEBIDA B WHERE B.QUANTIDADE BETWEEN 100 AND 300;


--FORNECEDOR

SELECT F.CNPJ, F.NOME, F.TELEFONE, D.BANCO, D.AGENCIA, D.CONTA, D.TIPO_CONTA
FROM FORNECEDOR F JOIN DADOS_BANCARIOS D ON F.DADOS_BANCARIOS = D.ID;

--CLIENTE

SELECT C.CPF, C.NOME, C.TEL_FIXO, C.TEL_MOVEL, D.BANCO, D.AGENCIA, D.CONTA, D.TIPO_CONTA, COUNT(*) AS NUMERO_FESTAS
FROM CLIENTE C JOIN DADOS_BANCARIOS D ON C.DADOS_BANCARIOS = D.ID
LEFT JOIN FESTA F ON C.CPF = F.CLIENTE
GROUP BY(C.CPF, C.NOME, C.TEL_FIXO, C.TEL_MOVEL, D.BANCO, D.AGENCIA, D.CONTA, D.TIPO_CONTA);
