
errors = {'UQ_ENDERECO' : 'Endereço já cadastrado',
	'CK_ENDERECO_CEP' : 'CEP inválido. Deve ser no formato XXXXX-XXX',
	'UQ_DADOS_BANCARIOS' : 'Dados bancários já cadastrados',
	'CK_TIPO_CONTA' : 'Tipo da conta deve ser CC ou CP',
	'FK_FORNECEDOR' : 'Dados bancários não encontrados',
	'CK_FORNECEDOR_CNPJ' : 'CNPJ inválido. Deve ser no formato XX.XXX.XXX/XXXX-XX',
	'CK_FORNECEDOR_TELEFONE' : 'Telefone inválido. Deve ser no formato (XX)XXXX-XXXX',
	'CK_FUNCIONARIO_CPF' : 'CPF inválido. Deve ser no formato XXX.XXX.XXX-XX',
	'CK_FUNCIONARIO_CARGO' : 'Cargo deve ser GARCOM, GERENTE, BARTENDER ou OPERADOR',
	'CK_FUNCIONARIO_TEL_MOVEL' : 'Telefone móvel inválido. Deve ser no formato (XX)9XXXX-XXXX',
	'CK_FUNCIONARIO_TEL_FIXO' : 'Telefone fixo inválido. Deve ser no formato (XX)XXXX-XXXX',
	'FK1_CLIENTE' : 'Dados bancários não encontrados',
	'FK2_CLIENTE' : 'Endereço não encontrado',
	'CK_CLIENTE_CPF' : 'CPF inválido. Deve ser no formato XXX.XXX.XXX-XX',
	'CK_CLIENTE_TEL_FIXO' : 'Telefone fixo inválido. Deve ser no formato (XX)XXXX-XXXX',
	'CK_CLIENTE_TEL_MOVEL' : 'Telefone móvel inválido. Deve ser no formato (XX)9XXXX-XXXX',
	'FK_CASA_FESTA' : 'Endereço não encontrado',
	'FK1_FESTA' : 'Cliente não encontrado',
	'FK2_FESTA' : 'Casa de Festa não encontrada',
	'FK3_FESTA' : 'Gerente não encontrado',
	'CK_FESTA_TIPO' : 'Tipo deve ser A ou C',
	'FK_ANIVERSARIO' : 'Festa não encontrada',
	'CK_FAIXA_ETARIA' : 'Faixa etária deve ser 0-3, 4-7, 8-13 ou 14+',
	'UQ_BARRACA_RASPADINHA' : 'Barraca de Raspadinha já cadastradas',
	'FK1_BARRACA_RASPADINHA' : 2,
	'FK2_BARRACA_RASPADINHA' : 3,
	'FK1_GARCOM_FESTA' : 1,
	'FK2_GARCOM_FESTA' : 2,
	'CK_BEBIDA' : 1,
	'FK1_BEBIDA_BANDEJA_FESTA' : 1,
	'FK2_BEBIDA_BANDEJA_FESTA' : 2,
}
