# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/fornecedor.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(457, 256)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(211, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nome_label = QtWidgets.QLabel(self.frame_2)
        self.nome_label.setObjectName("nome_label")
        self.gridLayout_2.addWidget(self.nome_label, 0, 0, 1, 1)
        self.nome_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.nome_lineEdit.setMaximumSize(QtCore.QSize(240, 440))
        self.nome_lineEdit.setMaxLength(75)
        self.nome_lineEdit.setObjectName("nome_lineEdit")
        self.gridLayout_2.addWidget(self.nome_lineEdit, 1, 0, 1, 2)
        self.cnpj_label = QtWidgets.QLabel(self.frame_2)
        self.cnpj_label.setObjectName("cnpj_label")
        self.gridLayout_2.addWidget(self.cnpj_label, 2, 0, 1, 1)
        self.cnpj_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.cnpj_lineEdit.setMaximumSize(QtCore.QSize(240, 440))
        self.cnpj_lineEdit.setObjectName("cnpj_lineEdit")
        self.gridLayout_2.addWidget(self.cnpj_lineEdit, 3, 0, 1, 2)
        self.tel_label = QtWidgets.QLabel(self.frame_2)
        self.tel_label.setObjectName("tel_label")
        self.gridLayout_2.addWidget(self.tel_label, 4, 0, 1, 1)
        self.tel_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.tel_lineEdit.setMaximumSize(QtCore.QSize(240, 440))
        self.tel_lineEdit.setObjectName("tel_lineEdit")
        self.gridLayout_2.addWidget(self.tel_lineEdit, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 1, 1)
        self.dadosBancarios_label = QtWidgets.QLabel(Dialog)
        self.dadosBancarios_label.setObjectName("dadosBancarios_label")
        self.gridLayout_3.addWidget(self.dadosBancarios_label, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 2, 1, 1, 1)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.banco_label = QtWidgets.QLabel(self.widget_2)
        self.banco_label.setObjectName("banco_label")
        self.gridLayout_4.addWidget(self.banco_label, 0, 0, 1, 1)
        self.banco_comboBox = QtWidgets.QComboBox(self.widget_2)
        self.banco_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.banco_comboBox.setObjectName("banco_comboBox")
        self.gridLayout_4.addWidget(self.banco_comboBox, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_2, 0, 0, 1, 3)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.agencia_label = QtWidgets.QLabel(self.widget)
        self.agencia_label.setObjectName("agencia_label")
        self.gridLayout.addWidget(self.agencia_label, 0, 0, 1, 1)
        self.conta_label = QtWidgets.QLabel(self.widget)
        self.conta_label.setObjectName("conta_label")
        self.gridLayout.addWidget(self.conta_label, 0, 1, 1, 1)
        self.agencia_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.agencia_lineEdit.setObjectName("agencia_lineEdit")
        self.gridLayout.addWidget(self.agencia_lineEdit, 1, 0, 1, 1)
        self.conta_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.conta_lineEdit.setObjectName("conta_lineEdit")
        self.gridLayout.addWidget(self.conta_lineEdit, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout_5.addWidget(self.widget, 1, 0, 1, 3)
        self.corrente_radioButton = QtWidgets.QRadioButton(self.frame)
        self.corrente_radioButton.setChecked(True)
        self.corrente_radioButton.setObjectName("corrente_radioButton")
        self.gridLayout_5.addWidget(self.corrente_radioButton, 2, 0, 1, 1)
        self.poupanca_radioButton = QtWidgets.QRadioButton(self.frame)
        self.poupanca_radioButton.setObjectName("poupanca_radioButton")
        self.gridLayout_5.addWidget(self.poupanca_radioButton, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.nome_lineEdit, self.cnpj_lineEdit)
        Dialog.setTabOrder(self.cnpj_lineEdit, self.tel_lineEdit)
        Dialog.setTabOrder(self.tel_lineEdit, self.banco_comboBox)
        Dialog.setTabOrder(self.banco_comboBox, self.agencia_lineEdit)
        Dialog.setTabOrder(self.agencia_lineEdit, self.conta_lineEdit)
        Dialog.setTabOrder(self.conta_lineEdit, self.corrente_radioButton)
        Dialog.setTabOrder(self.corrente_radioButton, self.poupanca_radioButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Fornecedor"))
        self.label.setText(_translate("Dialog", "Dados Pessoais"))
        self.nome_label.setText(_translate("Dialog", "Nome"))
        self.cnpj_label.setText(_translate("Dialog", "CNPJ"))
        self.cnpj_lineEdit.setInputMask(_translate("Dialog", "99.999.999/9999-99"))
        self.tel_label.setText(_translate("Dialog", "Telefone"))
        self.tel_lineEdit.setInputMask(_translate("Dialog", "(99)9999-9999"))
        self.dadosBancarios_label.setText(_translate("Dialog", "Dados Bancários"))
        self.banco_label.setText(_translate("Dialog", "Banco"))
        self.agencia_label.setText(_translate("Dialog", "Agência"))
        self.conta_label.setText(_translate("Dialog", "Conta"))
        self.agencia_lineEdit.setInputMask(_translate("Dialog", "9999"))
        self.conta_lineEdit.setInputMask(_translate("Dialog", "9999999999"))
        self.corrente_radioButton.setText(_translate("Dialog", "Corrente"))
        self.poupanca_radioButton.setText(_translate("Dialog", "Poupança"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

